<h1 style="color:black;">HW02 -Creating the Crime Dataset </h1>

**BY WASIM RAJA MONDAL**

<h3 style="color:black;"> 1. Creating a folder on my computer</h3>

In [2]:
!pwd #created a notebook and working inside the directory HW02

/Users/wasim/Desktop/HW02

<h3 style="color:black;"> 2. Create a Jupyter Notebook.</h3>

In [3]:
#!mkdir data #creating data folder inside HW02

In [4]:
!ls #showing all the files inside HW02 directory

HW02_MondalW.ipynb data

In [5]:
!ls /Users/wasim/Desktop/HW02/data #ensuring all the datafiles are inside data foleder

CantonPoliceDept.db       DispositionCategories.csv
Census_Subzone.csv        SubZones_Distance.csv

<h3 style="color:black;"> 3. Import Libraries</h3>

In [6]:
!pip install numpy #installing numpy
!pip install pandas #installing pandas
!pip install matplotlib #installing matplotlib
!pip install seaborn #installing seaborn
!pip install statsmodels #installing statmodel
!pip install scikit-learn #installing scikit learn
import numpy as np  #importing numpy
import pandas as pd #importing pandas
import seaborn as sns #importing seaborn
import pandas as pd #importing pandas
import statsmodels  #importing statmodels
import statsmodels.api as sm
import matplotlib.pyplot as plt
pd.set_option('display.max_columns',500) #allows for up to 500 columns to be displayed when viewing a dataframe
plt.style.use("seaborn-v0_8-whitegrid") ##a style that can be used for plots
import datetime as dt #importing datetime
from sqlalchemy import create_engine #import sqlalchemy

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.6)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: statsmodels in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.14.4)
Requirement already satisfied: numpy<3,>=1.22.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsmodels) (2.2.6)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

<h3 style="color:black;"> 4. Import Data provided in Homework02 Data folder in D2L</h3>

**4a. Create a connection to the database**

In [7]:
from sqlalchemy import create_engine
from sqlalchemy import text

In [8]:
engine = create_engine('sqlite:///data/CantonPoliceDept.db')
con=engine.connect()
print('connection is ok')

connection is ok

**4b. Import the data from Calls table**

In [9]:
from sqlalchemy import inspect
insp = inspect(engine)
print(insp.get_table_names())

['Calls', 'Disposition']

In [10]:
rs=con.execute(text("SELECT * from Calls"))
df_calls = pd.DataFrame(rs.fetchall()) #fetching all the data from calls table
df_calls.columns = rs.keys()
display(df_calls.head(2))
df_calls.info()

  Call_Number Subzone Complaint  Date_Received
0  08C-000010  ZONE1D  Burglary  9/18/08 10:36
1  08C-000011  ZONE2B  Burglary  9/18/08 10:44

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264881 entries, 0 to 264880
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Call_Number    264881 non-null  object
 1   Subzone        264881 non-null  object
 2   Complaint      264881 non-null  object
 3   Date_Received  264881 non-null  object
dtypes: object(4)
memory usage: 8.1+ MB

**4c. Import the Disposition table**

In [11]:
rs=con.execute(text("SELECT * from Disposition"))
df_disp = pd.DataFrame(rs.fetchall()) #fetching all the data from calls table
df_disp.columns = rs.keys()
display(df_disp.head(2))
df_disp.info()

  Call_Number DISP
0  08C-000001   FA
1  08C-000002  N25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991423 entries, 0 to 991422
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Call_Number  991423 non-null  object
 1   DISP         991423 non-null  object
dtypes: object(2)
memory usage: 15.1+ MB

**4d. Importing the DispositionCategories**

In [12]:
df_disp_cat = pd.read_csv('data/DispositionCategories.csv', index_col=None, header=0)

In [13]:
df_disp_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DISP         89 non-null     object
 1   DISPOSITION  91 non-null     object
dtypes: object(2)
memory usage: 1.6+ KB

**4e. Importing the CensusData**

In [14]:
df_census = pd.read_csv('data/Census_Subzone.csv', index_col=None, header=0)

In [15]:
df_census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Subzone                                   25 non-null     object
 1   SqFootage                                 25 non-null     float64
 2   HousingUnits                              25 non-null     int64
 3   Population                                25 non-null     int64
 4   Population_Male                           25 non-null     int64
 5   Population_Female                         25 non-null     int64
 6   Worked                                    25 non-null     int64
 7   Worked in a principal city                17 non-null     float64
 8   Worked outside any principal city         17 non-null     float64
 9   Workers who travel to work                25 non-null     int64
 10  Total time to work (minutes)              17 non-null     float64
 11  Drove alone to Work                       25 non-null     int64
 12  Carpooled to Work                         25 non-null     int64
 13  Population_3andover                       25 non-null     int64
 14  Enrolled in school                        25 non-null     int64
 15  Enrolled in nursery school, preschool     25 non-null     int64
 16  Enrolled in kindergarten                  25 non-null     int64
 17  Enrolled in college, undergraduate years  25 non-null     int64
 18  Graduate or professional school           25 non-null     int64
 19  Not enrolled in school                    25 non-null     int64
 20  Households_earnings                       25 non-null     int64
 21  Households_wageorsalaryincome             25 non-null     int64
 22  Households_selfemploymentincome           25 non-null     int64
 23  Households_interest_dividends             25 non-null     int64
 24  Households_SSI                            25 non-null     int64
 25  Households_publicassistanceincome         25 non-null     int64
 26  MedianAge_Total                           25 non-null     int64
 27  MedianAge_Male                            25 non-null     int64
 28  MedianAge_Female                          25 non-null     int64
 29  HouseholdIncome_Median                    25 non-null     int64
 30  HouseholdIncome_Median_under25            11 non-null     float64
 31  HouseholdIncome_Median_25to44             24 non-null     float64
 32  HouseholdIncome_Median_65andover          25 non-null     int64
 33  HouseholdIncome_Median_45to64             25 non-null     int64
 34  Income_PerCapita                          25 non-null     int64
dtypes: float64(6), int64(28), object(1)
memory usage: 7.0+ KB

**4f.Importing the df_spatial**

In [16]:
df_spatial = pd.read_csv('data/SubZones_Distance.csv', index_col=None, header=0)

In [17]:
df_spatial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ZONE    29 non-null     object
 1   ZONE5D  29 non-null     float64
 2   ZONE3X  29 non-null     float64
 3   ZONE1D  29 non-null     float64
 4   ZONE5B  29 non-null     float64
 5   ZONE6A  29 non-null     float64
 6   ZONE2C  29 non-null     float64
 7   ZONE3C  29 non-null     float64
 8   ZONE2B  29 non-null     float64
 9   ZONE7B  29 non-null     float64
 10  ZONE7D  29 non-null     float64
 11  ZONE4D  29 non-null     float64
 12  ZONE1A  29 non-null     float64
 13  ZONE1B  29 non-null     float64
 14  ZONE1C  29 non-null     float64
 15  ZONE5C  29 non-null     float64
 16  ZONE5A  29 non-null     float64
 17  ZONE3D  29 non-null     float64
 18  ZONE3E  29 non-null     float64
 19  ZONE3A  29 non-null     float64
 20  ZONE3B  29 non-null     float64
 21  ZONE7A  29 non-null     float64
 22  ZONE7C  29 non-null     float64
 23  ZONE2A  29 non-null     float64
 24  ZONE2D  29 non-null     float64
 25  ZONE4B  29 non-null     float64
 26  ZONE4C  29 non-null     float64
 27  ZONE4A  29 non-null     float64
 28  ZONE6C  29 non-null     float64
 29  ZONE6B  29 non-null     float64
dtypes: float64(29), object(1)
memory usage: 6.9+ KB

<h3 style="color:black;"> 5. Create and format df_calls and df_disp</h3>

**5.1 Formatting df_calls**

*5.1a. Create the MONTH, YEAR, WEEK column based on Date_Received*

In [18]:
# Convert to datetime
df_calls["Date_Received"] = pd.to_datetime(df_calls["Date_Received"])
# Day name
df_calls["Day_Name"] = df_calls["Date_Received"].dt.day_name()
# ISO week number
df_calls["WEEK"] = df_calls["Date_Received"].dt.isocalendar().week
# Month (numeric)
df_calls["MONTH"] = df_calls["Date_Received"].dt.month
# Year
df_calls["YEAR"] = df_calls["Date_Received"].dt.year
#displaying first two row of the updated dataframe
df_calls.head(2)

/var/folders/p1/pwvyyzw90ms7kks3m6v5fy940000gn/T/ipykernel_3528/2921474404.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_calls["Date_Received"] = pd.to_datetime(df_calls["Date_Received"])

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008

*5.1b. Creating YEAR_WEEK column*

In [19]:
#create YEAR_WEEK variable
def create_year_week(row):
    if row['MONTH']==12 and row['WEEK']==1:
         return f"{row['YEAR']+1}_1"
    elif row['MONTH']==1 and row['WEEK']==53:
         return f"{row['YEAR']-1}_53"
    else:
         return f"{row['YEAR']}_{row['WEEK']}"


#apply function to create the YEAR_WEEK column
df_calls['YEAR_WEEK'] = df_calls.apply(create_year_week, axis=1)
#displaying the updated dataframe
df_calls.head(2)

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38

*5.1c. Creating SUB_YEAR_WEEK column*

In [20]:
#create SUB_YEAR_WEEK variable
def create_sub_year_week(row):
    return f"{row['YEAR_WEEK']}_{row['Subzone']}"


#apply function to create the YEAR_WEEK column
df_calls['SUB_YEAR_WEEK'] = df_calls.apply(create_sub_year_week, axis=1)
#displaying the updated dataframe
df_calls.head(2)

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK,SUB_YEAR_WEEK
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1D
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38,2008_38_ZONE2B

*5.1d. Create Dummy Variables from the Day_Name column and concatenate it back to
df_calls*

In [21]:
# Create dummy variables (no prefix)
day_dummies = pd.get_dummies(df_calls["Day_Name"])
# Concatenate back to original dataframe
df_calls = pd.concat([df_calls, day_dummies], axis=1)
#checking first three rows if the dataframe to see the added column
df_calls.head(3)

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK,SUB_YEAR_WEEK,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1D,False,False,False,False,True,False,False
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38,2008_38_ZONE2B,False,False,False,False,True,False,False
2,08C-000020,ZONE1C,Assault,2008-09-18 11:52:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1C,False,False,False,False,True,False,False

*5.1e. Creating Dummy Variables from the MONTH column and concatenate it back to df_calls*

In [22]:
# Create dummy variables with prefix 'month'
month_dummies = pd.get_dummies(df_calls["MONTH"], prefix="month")


# Concatenate back to original dataframe
df_calls = pd.concat([df_calls, month_dummies], axis=1)

#checking updated df_calls
df_calls.head(2)

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK,SUB_YEAR_WEEK,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1D,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38,2008_38_ZONE2B,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False

*5.1f. Creating Dummy Variables from the Complaint column and concatenate it back to
df_calls*

In [23]:
# Create dummy variables with prefix 'call'
complaint_dummies = pd.get_dummies(df_calls["Complaint"], prefix="call")

# Concatenate back to original dataframe
df_calls = pd.concat([df_calls, complaint_dummies], axis=1)

##checking updated df_calls
df_calls.head(2)

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK,SUB_YEAR_WEEK,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12,call_Armed subject,call_Assault,call_Burglar alarm,call_Burglary,call_Disturbance,call_Domestic,call_FW FIREWORKS,call_Fight,call_Loitering,call_Message delivery,call_Noise complaint,call_Possible drugs present,call_Prowler,call_Public Intoxication,call_Shots fired,call_Special residence patrol,call_Special watch,call_Stalking,call_Suspicious activity,call_Trespassing,call_Vandalism,call_Welfare check
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1D,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38,2008_38_ZONE2B,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

**5.2 Create df_calls_subweek**

*5.2.a Create a copy*

In [24]:
# Create subset dataframe with a copy
df_calls_subweek = df_calls[
    ['SUB_YEAR_WEEK', 'Subzone', 'WEEK', 'MONTH', 'YEAR', 'YEAR_WEEK']
].copy()

Checking for 264881 records in df_calls_subweek

In [25]:
df_calls_subweek.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264881 entries, 0 to 264880
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   SUB_YEAR_WEEK  264881 non-null  object
 1   Subzone        264881 non-null  object
 2   WEEK           264881 non-null  UInt32
 3   MONTH          264881 non-null  int32
 4   YEAR           264881 non-null  int32
 5   YEAR_WEEK      264881 non-null  object
dtypes: UInt32(1), int32(2), object(3)
memory usage: 9.3+ MB

*5.2.b Dropping the duplicates based on SUB_YEAR_WEEK*

In [26]:
df_calls_subweek = df_calls_subweek.drop_duplicates('SUB_YEAR_WEEK')

We should have 12187 records after removing duplicates

In [27]:
df_calls_subweek.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12187 entries, 0 to 264776
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SUB_YEAR_WEEK  12187 non-null  object
 1   Subzone        12187 non-null  object
 2   WEEK           12187 non-null  UInt32
 3   MONTH          12187 non-null  int32
 4   YEAR           12187 non-null  int32
 5   YEAR_WEEK      12187 non-null  object
dtypes: UInt32(1), int32(2), object(3)
memory usage: 535.6+ KB

*5.2.c Creating the call_ALL column*

In [28]:
df_calls_subweek_gr=df_calls.groupby('SUB_YEAR_WEEK')['WEEK'].count().reset_index()
df_calls_subweek_gr = df_calls_subweek_gr.rename(columns={"WEEK": "call_ALL"})
df_calls_subweek_gr.head(5)

    SUB_YEAR_WEEK  call_ALL
0  2008_38_ZONE1A        16
1  2008_38_ZONE1B        16
2  2008_38_ZONE1C        19
3  2008_38_ZONE1D        17
4  2008_38_ZONE2A        13

*5.2.d.Merging df_calls_subweek_gr with df_calls_subweek*

In [29]:
df_calls_subweek = pd.merge(
    df_calls_subweek_gr,
    df_calls_subweek,
    how="inner",
    on="SUB_YEAR_WEEK"
)
df_calls_subweek.head()

    SUB_YEAR_WEEK  call_ALL Subzone  WEEK  MONTH  YEAR YEAR_WEEK
0  2008_38_ZONE1A        16  ZONE1A    38      9  2008   2008_38
1  2008_38_ZONE1B        16  ZONE1B    38      9  2008   2008_38
2  2008_38_ZONE1C        19  ZONE1C    38      9  2008   2008_38
3  2008_38_ZONE1D        17  ZONE1D    38      9  2008   2008_38
4  2008_38_ZONE2A        13  ZONE2A    38      9  2008   2008_38

**5.3Formatting df_disp**

*5.3.a Merge df_disp and df_disp_cat so that df_disp will have three columns*

In [30]:
df_disp = pd.merge(
    df_disp,
    df_disp_cat,
    how="inner",
    on="DISP"
)
df_disp.head()

  Call_Number DISP      DISPOSITION
0  08C-000001   FA   FA-FALSE ALARM
1  08C-000002  N25   N25-NO CONTACT
2  08C-000003   RF  RF-REPORT FILED
3  08C-000004  N25   N25-NO CONTACT
4  08C-000005  N25   N25-NO CONTACT

*5.3.b Droping DISP*

In [31]:
df_disp = df_disp.drop(columns=["DISP"])

In [32]:
df_disp.head()

  Call_Number      DISPOSITION
0  08C-000001   FA-FALSE ALARM
1  08C-000002   N25-NO CONTACT
2  08C-000003  RF-REPORT FILED
3  08C-000004   N25-NO CONTACT
4  08C-000005   N25-NO CONTACT

*5.3.c Creating Dummy Variables from the DISPOSITION column and concatenate it back to
df_disp*

In [33]:
disp_dummies = pd.get_dummies(
    df_disp["DISPOSITION"],
    prefix="disp",
    dtype="int8"  # forces 0/1 instead of True/False
)

df_disp = pd.concat([df_disp, disp_dummies], axis=1)
df_disp.head()

,Call_Number,DISPOSITION,disp_15-ARREST,disp_66-CANCEL,disp_9-VERBAL,disp_ADV-ADVICE GIVEN,disp_AST-ASSIST,disp_CI-CITY CITATION,disp_CLR-CLEARED BY DISPATCH,disp_CM-CIVIL MATTER,disp_COMP,disp_DISR,disp_Disregard,disp_Domestic Violence Report,disp_FA-FALSE ALARM,disp_FD-FOUNDED ALARM,disp_FI-FIELD INTERVIEW,disp_Gone on Arrival,disp_IRT Report,disp_K9 Report,disp_MC-STATE MISD CITATION,disp_MDT-BOLO'D MDT,disp_MSG-MESSAGE DELIVERED,disp_N25-NO CONTACT,disp_NR-NO REPORT,disp_Other,disp_PR-PROPERTY RETURNED,disp_RES-RESOLVED,disp_RF-REPORT FILED,disp_Runaway juvenile (entered NCIC),disp_SAT-SETTLED AMONG SELVES,disp_TES-TEST,disp_TI -TOW IN,disp_Truancy,disp_VA Hospital Alarm (Fire)
0,08C-000001,FA-FALSE ALARM,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,08C-000002,N25-NO CONTACT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,08C-000003,RF-REPORT FILED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,08C-000004,N25-NO CONTACT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,08C-000005,N25-NO CONTACT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

**5.4.Creating df_calls_disp**

In [34]:
df_calls_disp = pd.merge(
    df_calls,
    df_disp,
    how="inner",
    on="Call_Number"
)
df_calls_disp.head()

,Call_Number,Subzone,Complaint,Date_Received,Day_Name,WEEK,MONTH,YEAR,YEAR_WEEK,SUB_YEAR_WEEK,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12,call_Armed subject,call_Assault,call_Burglar alarm,call_Burglary,call_Disturbance,call_Domestic,call_FW FIREWORKS,call_Fight,call_Loitering,call_Message delivery,call_Noise complaint,call_Possible drugs present,call_Prowler,call_Public Intoxication,call_Shots fired,call_Special residence patrol,call_Special watch,call_Stalking,call_Suspicious activity,call_Trespassing,call_Vandalism,call_Welfare check,DISPOSITION,disp_15-ARREST,disp_66-CANCEL,disp_9-VERBAL,disp_ADV-ADVICE GIVEN,disp_AST-ASSIST,disp_CI-CITY CITATION,disp_CLR-CLEARED BY DISPATCH,disp_CM-CIVIL MATTER,disp_COMP,disp_DISR,disp_Disregard,disp_Domestic Violence Report,disp_FA-FALSE ALARM,disp_FD-FOUNDED ALARM,disp_FI-FIELD INTERVIEW,disp_Gone on Arrival,disp_IRT Report,disp_K9 Report,disp_MC-STATE MISD CITATION,disp_MDT-BOLO'D MDT,disp_MSG-MESSAGE DELIVERED,disp_N25-NO CONTACT,disp_NR-NO REPORT,disp_Other,disp_PR-PROPERTY RETURNED,disp_RES-RESOLVED,disp_RF-REPORT FILED,disp_Runaway juvenile (entered NCIC),disp_SAT-SETTLED AMONG SELVES,disp_TES-TEST,disp_TI -TOW IN,disp_Truancy,disp_VA Hospital Alarm (Fire)
0,08C-000010,ZONE1D,Burglary,2008-09-18 10:36:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1D,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,RF-REPORT FILED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,08C-000011,ZONE2B,Burglary,2008-09-18 10:44:00,Thursday,38,9,2008,2008_38,2008_38_ZONE2B,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,RF-REPORT FILED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,08C-000020,ZONE1C,Assault,2008-09-18 11:52:00,Thursday,38,9,2008,2008_38,2008_38_ZONE1C,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,RF-REPORT FILED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,08C-000029,ZONE3D,Burglar alarm,2008-09-18 12:23:00,Thursday,38,9,2008,2008_38,2008_38_ZONE3D,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Other,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,08C-000030,ZONE4B,Welfare check,2008-09-18 12:26:00,Thursday,38,9,2008,2008_38,2008_38_ZONE4B,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,RES-RESOLVED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [35]:
df_calls_disp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267266 entries, 0 to 267265
Data columns (total 85 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Call_Number                           267266 non-null  object
 1   Subzone                               267266 non-null  object
 2   Complaint                             267266 non-null  object
 3   Date_Received                         267266 non-null  datetime64[ns]
 4   Day_Name                              267266 non-null  object
 5   WEEK                                  267266 non-null  UInt32
 6   MONTH                                 267266 non-null  int32
 7   YEAR                                  267266 non-null  int32
 8   YEAR_WEEK                             267266 non-null  object
 9   SUB_YEAR_WEEK                         267266 non-null  object
 10  Friday                                267266 non-null  bool
 11  Monday                                267266 non-null  bool
 12  Saturday                              267266 non-null  bool
 13  Sunday                                267266 non-null  bool
 14  Thursday                              267266 non-null  bool
 15  Tuesday                               267266 non-null  bool
 16  Wednesday                             267266 non-null  bool
 17  month_1                               267266 non-null  bool
 18  month_2                               267266 non-null  bool
 19  month_3                               267266 non-null  bool
 20  month_4                               267266 non-null  bool
 21  month_5                               267266 non-null  bool
 22  month_6                               267266 non-null  bool
 23  month_7                               267266 non-null  bool
 24  month_8                               267266 non-null  bool
 25  month_9                               267266 non-null  bool
 26  month_10                              267266 non-null  bool
 27  month_11                              267266 non-null  bool
 28  month_12                              267266 non-null  bool
 29  call_Armed subject                    267266 non-null  bool
 30  call_Assault                          267266 non-null  bool
 31  call_Burglar alarm                    267266 non-null  bool
 32  call_Burglary                         267266 non-null  bool
 33  call_Disturbance                      267266 non-null  bool
 34  call_Domestic                         267266 non-null  bool
 35  call_FW FIREWORKS                     267266 non-null  bool
 36  call_Fight                            267266 non-null  bool
 37  call_Loitering                        267266 non-null  bool
 38  call_Message delivery                 267266 non-null  bool
 39  call_Noise complaint                  267266 non-null  bool
 40  call_Possible drugs present           267266 non-null  bool
 41  call_Prowler                          267266 non-null  bool
 42  call_Public Intoxication              267266 non-null  bool
 43  call_Shots fired                      267266 non-null  bool
 44  call_Special residence patrol         267266 non-null  bool
 45  call_Special watch                    267266 non-null  bool
 46  call_Stalking                         267266 non-null  bool
 47  call_Suspicious activity              267266 non-null  bool
 48  call_Trespassing                      267266 non-null  bool
 49  call_Vandalism                        267266 non-null  bool
 50  call_Welfare check                    267266 non-null  bool
 51  DISPOSITION                           267266 non-null  object
 52  disp_15-ARREST                        267266 non-null  int8
 53  disp_66-CANCEL                        267266 non-null  int8
 54  disp_9-VERBAL                         267266 non-null  int8
 55  disp_ADV-ADVICE GIVEN                 267266 non-null  int8
 56  disp_AST-ASSIST                       267266 non-null  int8
 57  disp_CI-CITY CITATION                 267266 non-null  int8
 58  disp_CLR-CLEARED BY DISPATCH          267266 non-null  int8
 59  disp_CM-CIVIL MATTER                  267266 non-null  int8
 60  disp_COMP                             267266 non-null  int8
 61  disp_DISR                             267266 non-null  int8
 62  disp_Disregard                        267266 non-null  int8
 63  disp_Domestic Violence Report         267266 non-null  int8
 64  disp_FA-FALSE ALARM                   267266 non-null  int8
 65  disp_FD-FOUNDED ALARM                 267266 non-null  int8
 66  disp_FI-FIELD INTERVIEW               267266 non-null  int8
 67  disp_Gone on Arrival                  267266 non-null  int8
 68  disp_IRT Report                       267266 non-null  int8
 69  disp_K9 Report                        267266 non-null  int8
 70  disp_MC-STATE MISD CITATION           267266 non-null  int8
 71  disp_MDT-BOLO'D MDT                   267266 non-null  int8
 72  disp_MSG-MESSAGE DELIVERED            267266 non-null  int8
 73  disp_N25-NO CONTACT                   267266 non-null  int8
 74  disp_NR-NO REPORT                     267266 non-null  int8
 75  disp_Other                            267266 non-null  int8
 76  disp_PR-PROPERTY RETURNED             267266 non-null  int8
 77  disp_RES-RESOLVED                     267266 non-null  int8
 78  disp_RF-REPORT FILED                  267266 non-null  int8
 79  disp_Runaway juvenile (entered NCIC)  267266 non-null  int8
 80  disp_SAT-SETTLED AMONG SELVES         267266 non-null  int8
 81  disp_TES-TEST                         267266 non-null  int8
 82  disp_TI -TOW IN                       267266 non-null  int8
 83  disp_Truancy                          267266 non-null  int8
 84  disp_VA Hospital Alarm (Fire)         267266 non-null  int8
dtypes: UInt32(1), bool(41), datetime64[ns](1), int32(2), int8(33), object(7)
memory usage: 38.5+ MB

**5.5 Summary for Section 5**

In section 5, we have prepared Calls and dispositions data. As we observe in Section 4, CantonPoliceDept.db has two important information in the form of table Calls and Disposition. We have prepared the dataframe df_calls from Calls table in Section 4. In this Section, we have looked into Date_Received in the df_calls and extracted information and created columns for Day_Name,WEEK,MONTH	and YEAR. Next, we created another column YEAR_WEEK where we stored YEAR and WEEK combined information in a fomrattted output. Next, we created another column SUB_YEAR_WEEK where we also combined zone information with YEAR and WEEK information. After that, we have created dummy variables from the Day_Name and Complaint so that in our df_calls  dataframe, we have week day information, month information and type of Calls information. Next, we create a new dataframe df_calls_subweek considering SUB_YEAR_WEEK, Subzone, WEEK, MONTH, YEAR, YEAR_WEEK columns from the df_calls dataframe. Initially, there were lot of dublicates in this dataframe. We removed all these dublicate entries and we find 12187 records after removing duplicates. Next, we groups all call records by subzone–year–week and select the WEEK column within each group and count total number of calls in that SUB_YEAR_WEEK and rename the WEEK column to call_ALL. All these information we store in new dataframe df_calls_subweek_gr. Next, we merge the df_calls_subweek_gr with df_calls_subweek depending on the same SUB_YEAR_WEEK. Thus, we prepare df_calls_subweek dataframe. We perform similar operations for dispositions and prepare final dataframe for df_calls_disp.

<h3 style="color:black;"> 6. Census Data</h3>

*6.1Formatting df_census*

*6.1.a Remove any column that has less than 20 non-null values.*

In [36]:
df_census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Subzone                                   25 non-null     object
 1   SqFootage                                 25 non-null     float64
 2   HousingUnits                              25 non-null     int64
 3   Population                                25 non-null     int64
 4   Population_Male                           25 non-null     int64
 5   Population_Female                         25 non-null     int64
 6   Worked                                    25 non-null     int64
 7   Worked in a principal city                17 non-null     float64
 8   Worked outside any principal city         17 non-null     float64
 9   Workers who travel to work                25 non-null     int64
 10  Total time to work (minutes)              17 non-null     float64
 11  Drove alone to Work                       25 non-null     int64
 12  Carpooled to Work                         25 non-null     int64
 13  Population_3andover                       25 non-null     int64
 14  Enrolled in school                        25 non-null     int64
 15  Enrolled in nursery school, preschool     25 non-null     int64
 16  Enrolled in kindergarten                  25 non-null     int64
 17  Enrolled in college, undergraduate years  25 non-null     int64
 18  Graduate or professional school           25 non-null     int64
 19  Not enrolled in school                    25 non-null     int64
 20  Households_earnings                       25 non-null     int64
 21  Households_wageorsalaryincome             25 non-null     int64
 22  Households_selfemploymentincome           25 non-null     int64
 23  Households_interest_dividends             25 non-null     int64
 24  Households_SSI                            25 non-null     int64
 25  Households_publicassistanceincome         25 non-null     int64
 26  MedianAge_Total                           25 non-null     int64
 27  MedianAge_Male                            25 non-null     int64
 28  MedianAge_Female                          25 non-null     int64
 29  HouseholdIncome_Median                    25 non-null     int64
 30  HouseholdIncome_Median_under25            11 non-null     float64
 31  HouseholdIncome_Median_25to44             24 non-null     float64
 32  HouseholdIncome_Median_65andover          25 non-null     int64
 33  HouseholdIncome_Median_45to64             25 non-null     int64
 34  Income_PerCapita                          25 non-null     int64
dtypes: float64(6), int64(28), object(1)
memory usage: 7.0+ KB

In [37]:
df_census = df_census.dropna(axis=1, thresh=20)

*6.1.bFor HouseholdIncome_Median_25to44, fill in any null values with the mean.*

In [38]:
df_census["HouseholdIncome_Median_25to44"] = (
    df_census["HouseholdIncome_Median_25to44"]
    .fillna(df_census["HouseholdIncome_Median_25to44"].mean())
)

**6.2 Converting Columns from totals to ratios**

In [39]:
# ---- Ratios based on Total Population ----
df_census["Population_Male"] = (
    df_census["Population_Male"] / df_census["Population"]
)

df_census["Population_Female"] = (
    df_census["Population_Female"] / df_census["Population"]
)


# ---- Ratios based on Worked ----
df_census["Workers who travel to work"] = (
    df_census["Workers who travel to work"] / df_census["Worked"]
)

df_census["Drove alone to Work"] = (
    df_census["Drove alone to Work"] / df_census["Worked"]
)

df_census["Carpooled to Work"] = (
    df_census["Carpooled to Work"] / df_census["Worked"]
)


# ---- Ratios based on Population_3andover ----
school_base = df_census["Population_3andover"]

df_census["Enrolled in school"] = (
    df_census["Enrolled in school"] / school_base
)

df_census["Enrolled in nursery school, preschool"] = (
    df_census["Enrolled in nursery school, preschool"] / school_base
)

df_census["Enrolled in kindergarten"] = (
    df_census["Enrolled in kindergarten"] / school_base
)

df_census["Enrolled in college, undergraduate years"] = (
    df_census["Enrolled in college, undergraduate years"] / school_base
)

df_census["Graduate or professional school"] = (
    df_census["Graduate or professional school"] / school_base
)

df_census["Not enrolled in school"] = (
    df_census["Not enrolled in school"] / school_base
)


# ---- Ratios based on Households_earnings ----
hh_base = df_census["Households_earnings"]

df_census["Households_wageorsalaryincome"] = (
    df_census["Households_wageorsalaryincome"] / hh_base
)

df_census["Households_selfemploymentincome"] = (
    df_census["Households_selfemploymentincome"] / hh_base
)

df_census["Households_interest_dividends"] = (
    df_census["Households_interest_dividends"] / hh_base
)

df_census["Households_SSI"] = (
    df_census["Households_SSI"] / hh_base
)

df_census["Households_publicassistanceincome"] = (
    df_census["Households_publicassistanceincome"] / hh_base
)

In [40]:
df_census.describe().T

,count,mean,std,min,25%,50%,75%,max
SqFootage,25.0,6.732195e+07,5.185345e+07,194076.367400,2.741946e+07,6.580327e+07,8.392070e+07,1.939506e+08
HousingUnits,25.0,1.515600e+02,1.085933e+02,30.000000,6.700000e+01,1.190000e+02,2.270000e+02,3.930000e+02
Population,25.0,6.661600e+03,5.613112e+03,626.000000,2.866000e+03,4.503000e+03,8.040000e+03,2.220300e+04
Population_Male,25.0,4.840106e-01,5.260814e-02,0.322684,4.659171e-01,4.880496e-01,5.062229e-01,5.786925e-01
Population_Female,25.0,5.159894e-01,5.260814e-02,0.421308,4.937771e-01,5.119504e-01,5.340829e-01,6.773163e-01
Worked,25.0,3.380560e+03,2.948367e+03,317.000000,1.495000e+03,2.366000e+03,3.991000e+03,1.229400e+04
Workers who travel to work,25.0,9.694941e-01,1.920295e-02,0.929227,9.521587e-01,9.706590e-01,9.859532e-01,1.000000e+00
Drove alone to Work,25.0,8.607563e-01,5.626018e-02,0.680988,8.329186e-01,8.742058e-01,8.981723e-01,9.700399e-01
Carpooled to Work,25.0,8.307507e-02,4.462331e-02,0.010652,5.600933e-02,6.844337e-02,9.596592e-02,2.251852e-01
Population_3andover,25.0,6.411520e+03,5.375156e+03,606.000000,2.798000e+03,4.358000e+03,7.621000e+03,2.105500e+04
Enrolled in school,25.0,2.854654e-01,7.940241e-02,0.145215,2.642056e-01,2.873521e-01,3.133069e-01,5.586767e-01
"Enrolled in nursery school, preschool",25.0,1.479506e-02,1.262069e-02,0.000000,7.887090e-03,1.247533e-02,1.726370e-02,4.913558e-02
Enrolled in kindergarten,25.0,1.384460e-02,1.040210e-02,0.000000,6.569460e-03,1.333704e-02,1.910828e-02,3.658537e-02
"Enrolled in college, undergraduate years",25.0,9.101016e-02,8.824316e-02,0.021086,3.726545e-02,6.267660e-02,9.474854e-02,4.065779e-01
Graduate or professional school,25.0,1.455681e-02,1.203518e-02,0.000000,5.783386e-03,1.121615e-02,2.066803e-02,4.431892e-02
Not enrolled in school,25.0,7.145346e-01,7.940241e-02,0.441323,6.866931e-01,7.126479e-01,7.357944e-01,8.547855e-01
Households_earnings,25.0,2.073320e+03,1.762541e+03,229.000000,8.690000e+02,1.313000e+03,2.492000e+03,7.223000e+03
Households_wageorsalaryincome,25.0,9.710041e-01,2.293561e-02,0.936196,9.530262e-01,9.733884e-01,9.906778e-01,1.000000e+00
Households_selfemploymentincome,25.0,1.268414e-01,5.571781e-02,0.042245,9.509202e-02,1.245136e-01,1.588032e-01,2.969432e-01
Households_interest_dividends,25.0,1.960384e-01,8.271586e-02,0.040698,1.363699e-01,1.782101e-01,2.743764e-01,3.310392e-01
Households_SSI,25.0,4.857562e-02,5.102860e-02,0.003968,2.178988e-02,3.280569e-02,5.102818e-02,1.841652e-01
Households_publicassistanceincome,25.0,2.821240e-02,2.813647e-02,0.000000,1.169993e-02,2.327448e-02,3.777209e-02,1.153184e-01
MedianAge_Total,25.0,3.492000e+01,5.537147e+00,23.000000,3.300000e+01,3.500000e+01,3.700000e+01,4.500000e+01
MedianAge_Male,25.0,3.396000e+01,5.223983e+00,23.000000,3.100000e+01,3.400000e+01,3.700000e+01,4.800000e+01
MedianAge_Female,25.0,3.576000e+01,6.240192e+00,23.000000,3.200000e+01,3.600000e+01,4.000000e+01,4.600000e+01
HouseholdIncome_Median,25.0,5.885328e+04,2.194478e+04,22150.000000,4.593700e+04,5.702900e+04,7.456000e+04,1.048830e+05
HouseholdIncome_Median_25to44,25.0,6.507829e+04,2.156226e+04,31089.000000,4.787300e+04,6.471600e+04,8.269600e+04,1.035160e+05
HouseholdIncome_Median_65andover,25.0,4.746536e+04,2.031620e+04,15750.000000,3.204500e+04,4.721400e+04,6.174500e+04,9.781300e+04
HouseholdIncome_Median_45to64,25.0,6.919896e+04,2.475480e+04,27679.000000,5.473300e+04,6.386500e+04,8.461700e+04,1.186670e+05
Income_PerCapita,25.0,2.657684e+04,7.397247e+03,14181.000000,2.227100e+04,2.667500e+04,3.084400e+04,4.109700e+04

**6.3 Summary for Section 6**

In this Section 6, Format the Census Data so that it is ready to be merge with the call and
disposition data. First, we format the  df_census by removing any column that has less than 20 non-null values and fill in any null values with the mean for HouseholdIncome_Median_25to44.

As a step-2, we convert Columns from totals to ratios. For example, Population_Male Ratio based on ‘Total Population’
Population_Female Ratio based on ‘Total Population’
Workers who travel to work Ratio based on ‘Worked’
Drove alone to Work Ratio based on ‘Worked’
Carpooled to Work Ratio based on ‘Worked’
Enrolled in school Ratio based on ‘Population_3andover’
Enrolled in nursery school, preschool Ratio based on ‘Population_3andover’
Enrolled in kindergarten Ratio based on ‘Population_3andover’
Enrolled in college, undergraduate years Ratio based on ‘Population_3andover’
Graduate or professional school Ratio based on ‘Population_3andover’
Not enrolled in school Ratio based on ‘Population_3andover’
Households_wageorsalaryincome Ratio based on ‘Households_earnings
Households_selfemploymentincome Ratio based on ‘Households_earnings
Households_interest_dividends Ratio based on ‘Households_earnings
Households_SSI Ratio based on ‘Households_earnings
Households_publicassistanceincome Ratio based on ‘Households_earnings

<h3 style="color:black;"> 7. Create the combine dataset based on SUB_YEAR_WEEK</h3>

**7.1. Create df_calls_disp_week**

In [41]:
#Create df_calls_disp_week by creating a copy of df_calls_disp.
df_calls_disp_week = df_calls_disp.copy()

In [42]:
#Drop the following columns from df_calls_disp_week
df_calls_disp_week = df_calls_disp_week.drop(
    columns=[
        "Subzone",
        "Call_Number",
        "Complaint",
        "Date_Received",
        "Day_Name",
        "WEEK",
        "MONTH",
        "YEAR",
        "YEAR_WEEK",
        "DISPOSITION",
    ]
)

In [43]:
#Group df_calls_week by SUB_YEAR_WEEK by summing up all of the columns as integers
df_calls_disp_week =df_calls_disp_week.groupby('SUB_YEAR_WEEK').sum().astype(int).reset_index()

In [44]:
#df_calls_disp_week should include 12,169 records and 75 columns.
df_calls_disp_week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12169 entries, 0 to 12168
Data columns (total 75 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   SUB_YEAR_WEEK                         12169 non-null  object
 1   Friday                                12169 non-null  int64
 2   Monday                                12169 non-null  int64
 3   Saturday                              12169 non-null  int64
 4   Sunday                                12169 non-null  int64
 5   Thursday                              12169 non-null  int64
 6   Tuesday                               12169 non-null  int64
 7   Wednesday                             12169 non-null  int64
 8   month_1                               12169 non-null  int64
 9   month_2                               12169 non-null  int64
 10  month_3                               12169 non-null  int64
 11  month_4                               12169 non-null  int64
 12  month_5                               12169 non-null  int64
 13  month_6                               12169 non-null  int64
 14  month_7                               12169 non-null  int64
 15  month_8                               12169 non-null  int64
 16  month_9                               12169 non-null  int64
 17  month_10                              12169 non-null  int64
 18  month_11                              12169 non-null  int64
 19  month_12                              12169 non-null  int64
 20  call_Armed subject                    12169 non-null  int64
 21  call_Assault                          12169 non-null  int64
 22  call_Burglar alarm                    12169 non-null  int64
 23  call_Burglary                         12169 non-null  int64
 24  call_Disturbance                      12169 non-null  int64
 25  call_Domestic                         12169 non-null  int64
 26  call_FW FIREWORKS                     12169 non-null  int64
 27  call_Fight                            12169 non-null  int64
 28  call_Loitering                        12169 non-null  int64
 29  call_Message delivery                 12169 non-null  int64
 30  call_Noise complaint                  12169 non-null  int64
 31  call_Possible drugs present           12169 non-null  int64
 32  call_Prowler                          12169 non-null  int64
 33  call_Public Intoxication              12169 non-null  int64
 34  call_Shots fired                      12169 non-null  int64
 35  call_Special residence patrol         12169 non-null  int64
 36  call_Special watch                    12169 non-null  int64
 37  call_Stalking                         12169 non-null  int64
 38  call_Suspicious activity              12169 non-null  int64
 39  call_Trespassing                      12169 non-null  int64
 40  call_Vandalism                        12169 non-null  int64
 41  call_Welfare check                    12169 non-null  int64
 42  disp_15-ARREST                        12169 non-null  int64
 43  disp_66-CANCEL                        12169 non-null  int64
 44  disp_9-VERBAL                         12169 non-null  int64
 45  disp_ADV-ADVICE GIVEN                 12169 non-null  int64
 46  disp_AST-ASSIST                       12169 non-null  int64
 47  disp_CI-CITY CITATION                 12169 non-null  int64
 48  disp_CLR-CLEARED BY DISPATCH          12169 non-null  int64
 49  disp_CM-CIVIL MATTER                  12169 non-null  int64
 50  disp_COMP                             12169 non-null  int64
 51  disp_DISR                             12169 non-null  int64
 52  disp_Disregard                        12169 non-null  int64
 53  disp_Domestic Violence Report         12169 non-null  int64
 54  disp_FA-FALSE ALARM                   12169 non-null  int64
 55  disp_FD-FOUNDED ALARM                 12169 non-null  int64
 56  disp_FI-FIELD INTERVIEW               12169 non-null  int64
 57  disp_Gone on Arrival                  12169 non-null  int64
 58  disp_IRT Report                       12169 non-null  int64
 59  disp_K9 Report                        12169 non-null  int64
 60  disp_MC-STATE MISD CITATION           12169 non-null  int64
 61  disp_MDT-BOLO'D MDT                   12169 non-null  int64
 62  disp_MSG-MESSAGE DELIVERED            12169 non-null  int64
 63  disp_N25-NO CONTACT                   12169 non-null  int64
 64  disp_NR-NO REPORT                     12169 non-null  int64
 65  disp_Other                            12169 non-null  int64
 66  disp_PR-PROPERTY RETURNED             12169 non-null  int64
 67  disp_RES-RESOLVED                     12169 non-null  int64
 68  disp_RF-REPORT FILED                  12169 non-null  int64
 69  disp_Runaway juvenile (entered NCIC)  12169 non-null  int64
 70  disp_SAT-SETTLED AMONG SELVES         12169 non-null  int64
 71  disp_TES-TEST                         12169 non-null  int64
 72  disp_TI -TOW IN                       12169 non-null  int64
 73  disp_Truancy                          12169 non-null  int64
 74  disp_VA Hospital Alarm (Fire)         12169 non-null  int64
dtypes: int64(74), object(1)
memory usage: 7.0+ MB

In [45]:
#Merge df_calls_subweek and df_calls_disp_week
df_calls_disp_week = pd.merge(
    df_calls_subweek,
    df_calls_disp_week,
    how="inner",
    on="SUB_YEAR_WEEK"
)

In [46]:
#Merge df_calls_disp_week and df_census
df_calls_disp_week = pd.merge(
    df_calls_disp_week,
    df_census,
    how="inner",
    on="Subzone"
)

In [47]:
#Should have 111 columns and 12,169 records
df_calls_disp_week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12169 entries, 0 to 12168
Columns: 111 entries, SUB_YEAR_WEEK to Income_PerCapita
dtypes: Int64(1), UInt32(1), float64(18), int32(2), int64(86), object(3)
memory usage: 10.2+ MB

**7.2. Summary for Section 7**

The main objective of section 7 is to combine df_calls_subweek, df_calls_disp, and df_census based on SUB_YEAR_WEEK.
As a first step, we create df_calls_disp_week. We begin with copying the dataframe from df_calls_disp and dropping the following columns from df_calls_disp_week: 'Subzone','Call_Number', 'Complaint', 'Date_Received', 'Day_Name', 'WEEK', 'MONTH', 'YEAR', 'YEAR_WEEK', 'DISPOSITION. 

Next, we group df_calls_week by SUB_YEAR_WEEK by summing up all of the columns as integers. We finally observe that the df_calls_disp_week  has 12,169 records and 75 columns.

<h3 style="color:black;"> 8. Create Spatial Lag</h3>

**8.1 Create df_spatial**

In [48]:
df_spatial.head()

,ZONE,ZONE5D,ZONE3X,ZONE1D,ZONE5B,ZONE6A,ZONE2C,ZONE3C,ZONE2B,ZONE7B,ZONE7D,ZONE4D,ZONE1A,ZONE1B,ZONE1C,ZONE5C,ZONE5A,ZONE3D,ZONE3E,ZONE3A,ZONE3B,ZONE7A,ZONE7C,ZONE2A,ZONE2D,ZONE4B,ZONE4C,ZONE4A,ZONE6C,ZONE6B
0,ZONE5D,0.00000,61752.50885,27952.86211,19900.40012,53707.05555,35654.00130,40667.28582,46895.96176,22525.86888,7746.724534,39803.54835,32080.033990,30292.617730,27447.943980,16008.635290,21644.372500,34678.56404,31858.25789,48597.881810,47219.26714,23255.588060,17048.67725,37186.62023,38708.34665,54409.36913,44499.20197,61263.15503,37613.23598,46676.999730
1,ZONE3X,61752.50885,0.00000,38991.87517,41993.26308,13123.37308,45672.22149,21197.33872,51900.60212,53691.31900,57821.142290,32676.64218,32737.538150,32726.954880,36714.165600,46420.475880,40110.984480,28094.29090,29896.99385,13242.764400,15441.36004,44835.742000,55945.75803,39515.79331,58418.31296,43731.86705,36752.53272,32365.40902,28707.97478,22778.967950
2,ZONE1D,27952.86211,38991.87517,0.00000,11908.00676,28114.04553,13406.93212,19171.32744,25792.10749,14787.10212,21532.948730,11871.28135,6326.566288,7993.116351,4269.549039,12819.127270,12851.622500,11732.23014,14754.71233,26271.303280,28054.72454,5958.130244,17173.72225,10994.76894,24712.53123,28753.08451,17447.38708,33403.00262,10791.63848,19519.936580
3,ZONE5B,19900.40012,41993.26308,11908.00676,0.00000,33912.97688,24570.06846,20825.14348,37160.63945,19157.88151,16151.513120,22763.47460,13320.022370,10741.505670,9138.713476,4759.381157,2481.732459,14873.85320,12259.01631,28780.675480,27962.07403,11519.130220,17757.12480,22902.03329,33863.68889,40630.10219,29140.51580,44013.31922,18753.55049,27609.275780
4,ZONE6A,53707.05555,13123.37308,28114.04553,33912.97688,0.00000,32971.35649,14521.04349,38778.09899,42309.23527,48648.659030,20025.29223,22306.576810,23442.863920,26793.725550,37756.721310,32564.364340,19044.28534,23207.07866,9307.597112,15340.82921,34071.841750,45282.95595,26824.46055,45538.91123,31015.32700,23638.65055,21468.21474,17336.84299,9893.639573

In [49]:
#Create a list of the column names from df_spatial and name it df_spatial_col
df_spatial_col = df_spatial.columns

In [50]:
#Drop ‘ZONE’ from df_spatial_col
df_spatial_col = df_spatial_col.drop("ZONE")

In [51]:
#Create a melt of df_spatial (This converts the crosstab into three total columns)
df_spatial_melt = pd.melt(
    df_spatial,
    id_vars="ZONE",
    value_vars=df_spatial_col
)

In [52]:
#Rename the columns in df_spatial_melt
df_spatial_melt = df_spatial_melt.rename(
    columns={
        "ZONE": "Subzone",
        "value": "Subzone_Dist",
        "variable": "Subzone_Comp"
    }
)

In [53]:
df_spatial_melt.head()

  Subzone Subzone_Comp  Subzone_Dist
0  ZONE5D       ZONE5D       0.00000
1  ZONE3X       ZONE5D   61752.50885
2  ZONE1D       ZONE5D   27952.86211
3  ZONE5B       ZONE5D   19900.40012
4  ZONE6A       ZONE5D   53707.05555

In [54]:
#Drop the rows where Subzone_dist = 0 in df_spatial_melt
df_spatial_melt = df_spatial_melt[df_spatial_melt['Subzone_Dist'] > 0]

In [55]:
#Drop the rows where Subzone_dist = 0 in df_spatial_melt
#Drop all rows where Subzone_dist >=12,000
df_spatial_melt = df_spatial_melt[
    (df_spatial_melt["Subzone_Dist"] > 0) &
    (df_spatial_melt["Subzone_Dist"] < 12000)
]

In [56]:
#should have 122 records remaining
len(df_spatial_melt)

122

**8.2 Create df_burglary_week**

In [57]:
#Create df_burglary_week by creating a copy of the following columns from df_calls_disp_week
df_burglary_week = df_calls_disp_week[["SUB_YEAR_WEEK", "Subzone", "call_ALL", "call_Burglary"]].copy()

In [58]:
#Merge df_spatial_melt and df_burglary_week together to create df_spatial_burg
df_spatial_burg = pd.merge(
    df_spatial_melt,
    df_burglary_week,
    how="inner",
    left_on=["Subzone_Comp"],
    right_on=["Subzone"]
)

In [59]:
#Drop ‘Subzone_y’ and ‘Subzone_dist’
df_spatial_burg = df_spatial_burg.drop(columns=["Subzone_y", "Subzone_Dist"])

In [60]:
#Rename ‘Subzone_x’ to ‘Subzone’ 
df_spatial_burg = df_spatial_burg.rename(columns={"Subzone_x": "Subzone"})

In [61]:
#Create a dictionary that contains all subzones as a keys and the list of their neighbors as the values
subzone_neighbors = {}

for i in range(len(df_spatial_melt)):
    zone = df_spatial_melt.iloc[i, 0]
    
    if zone not in subzone_neighbors:
        subzone_neighbors[zone] = []
    
    subzone_neighbors[zone].append(df_spatial_melt.iloc[i, 1])

In [62]:
# Create a dictionary where you save the sum of call_ALL of each neighboring subzone

dict = subzone_neighbors  

dict2 = {}

for i in range(len(df_spatial_burg)):
    key = df_spatial_burg.iloc[i, 2]   # keys are the values in column SUB_YEAR_WEEK
    zone = key[-6:]                    # gives ZONE7D from 2018_9_ZONE7D
    year_week = key[:-6]               # gives 2018_9_ from 2018_9_ZONE7D

    neighbours = []

    if zone in dict:
        neighbours = dict[zone]

    accumulate = 0

    if len(neighbours) > 0:
        if key not in dict2:
            dict2[key] = 0

            for neigh in neighbours:
                value = year_week + neigh

                call_all = df_spatial_burg[
                    df_spatial_burg.SUB_YEAR_WEEK == value
                ]['call_ALL']

                if call_all.empty == False:
                    call_all = call_all.values[0]
                    dict2[key] += int(call_all)

In [63]:
#Convert the dictionary to the data frame
results1 = pd.DataFrame.from_dict(dict2, orient ='index').reset_index()

In [64]:
#renaming the column
results1 = results1.rename(columns = {'index':'SUB_YEAR_WEEK', 0:'call_ALL_comp'})

In [65]:
# Create a dictionary where you save the sum of call_Burglary of each neighboring subzone

dict = subzone_neighbors  

dict3 = {}

for i in range(len(df_spatial_burg)):
    key = df_spatial_burg.iloc[i, 2]   # keys are the values in column SUB_YEAR_WEEK
    zone = key[-6:]                    # gives ZONE7D from 2018_9_ZONE7D
    year_week = key[:-6]               # gives 2018_9_ from 2018_9_ZONE7D

    neighbours = []

    if zone in dict:
        neighbours = dict[zone]

    accumulate = 0

    if len(neighbours) > 0:
        if key not in dict3:
            dict3[key] = 0

            for neigh in neighbours:
                value = year_week + neigh

                call_burg = df_spatial_burg[
                    df_spatial_burg.SUB_YEAR_WEEK == value
                ]['call_Burglary']

                if call_burg.empty == False:
                    call_burg = call_burg.values[0]
                    dict3[key] += int(call_burg)


# Convert dict3 to dataframe and rename columns
results2 = pd.DataFrame.from_dict(dict3, orient='index').reset_index()
results2 = results2.rename(columns={'index': 'SUB_YEAR_WEEK', 0: 'call_Burglary_comp'})

In [66]:
#Merge the data frames results1 and results2
df_spatial_burg_comp = pd.merge(
    results1,
    results2,
    how="inner",
    on="SUB_YEAR_WEEK"
)
df_spatial_burg_comp.shape

(11626, 3)

In [67]:
#Merge df_calls_disp_week and df_spatial_burg_comp
df_calls_disp_week = pd.merge(
    df_calls_disp_week,
    df_spatial_burg_comp,
    how="left",
    on=["SUB_YEAR_WEEK"]
)

In [68]:
#Fill in null values for call_ALL_comp and call_Burglary_comp with 0
df_calls_disp_week[["call_ALL_comp", "call_Burglary_comp"]] = (
    df_calls_disp_week[["call_ALL_comp", "call_Burglary_comp"]].fillna(0)
)

In [69]:
df_calls_disp_week.shape

(12169, 113)

**8.3.Summary for Section 8**

One of the keys attributes of predicting future crimes or activities is to see what
is happening in the surrounding subzones. For example, if there are a lot of burglaries in one
neighborhood (Subzone ZONE2A) there is an assumption by the Canton Police that the
Subzones next to ZONE2A will have burglaries next week. Therefore, in this Section 8, we create
columns that show activity around each Subzone. It will be very helpful in a predictive model using df_calls_disp_week. 


Based on this motivations, as a first step, we create df_spatial dataframe. Next, we create df_burglary_week dataframe.

<h3 style="color:black;"> 9. Create Time Lag</h3>

**9.1 Create df_calls_subweek_target**

In [70]:
#Create a new DataFrame named df_calls_subweek_target which is a copy ofdf_calls_subweek
df_calls_subweek_target = df_calls_subweek.copy()

In [71]:
#Merge df_calls_subweek_target with df_calls_disp_week[['SUB_YEAR_WEEK','call_Burglary']].
df_calls_subweek_target = pd.merge(
    df_calls_subweek_target,
    df_calls_disp_week[["SUB_YEAR_WEEK", "call_Burglary"]],
    how="inner",
    on="SUB_YEAR_WEEK"
)

In [72]:
df_calls_subweek_target.head()

,SUB_YEAR_WEEK,call_ALL,Subzone,WEEK,MONTH,YEAR,YEAR_WEEK,call_Burglary
0,2008_38_ZONE1A,16,ZONE1A,38,9,2008,2008_38,3
1,2008_38_ZONE1B,16,ZONE1B,38,9,2008,2008_38,1
2,2008_38_ZONE1C,19,ZONE1C,38,9,2008,2008_38,0
3,2008_38_ZONE1D,17,ZONE1D,38,9,2008,2008_38,1
4,2008_38_ZONE2A,13,ZONE2A,38,9,2008,2008_38,0

In [73]:
# Create a real week-date from YEAR + WEEK (ISO week), then shift +1 week
week_start = pd.to_datetime(
    df_calls_subweek_target["YEAR"].astype(str)
    + "-W"
    + df_calls_subweek_target["WEEK"].astype(int).astype(str).str.zfill(2)
    + "-1",
    format="%G-W%V-%u",
    errors="coerce"
)

target_week_start = week_start + pd.Timedelta(weeks=1)

In [74]:
# Extract target ISO YEAR/WEEK (handles week 52/53 rollover automatically)
iso = target_week_start.dt.isocalendar()
df_calls_subweek_target["YEAR_target"] = iso["year"].astype(int)
df_calls_subweek_target["WEEK_target"] = iso["week"].astype(int)

In [75]:
#  Create YEAR_WEEK_target and SUB_YEAR_WEEK_target
df_calls_subweek_target["YEAR_WEEK_target"] = (
    df_calls_subweek_target["YEAR_target"].astype(str) + "_" +
    df_calls_subweek_target["WEEK_target"].astype(str)
)

df_calls_subweek_target["SUB_YEAR_WEEK_target"] = (
    df_calls_subweek_target["YEAR_WEEK_target"] + "_" +
    df_calls_subweek_target["Subzone"].astype(str)
)
#  Build a lookup table of next-week outcomes (from current-week values)
lookup = df_calls_subweek_target[["SUB_YEAR_WEEK", "call_ALL", "call_Burglary"]].copy()
lookup = lookup.rename(columns={
    "SUB_YEAR_WEEK": "SUB_YEAR_WEEK_target",
    "call_ALL": "call_ALL_target",
    "call_Burglary": "call_Burglary_target"
})

#  Merge targets onto the current week rows
df_calls_subweek_target = pd.merge(
    df_calls_subweek_target,
    lookup,
    how="left",
    on="SUB_YEAR_WEEK_target"
)

In [76]:
df_calls_subweek_target.head()

,SUB_YEAR_WEEK,call_ALL,Subzone,WEEK,MONTH,YEAR,YEAR_WEEK,call_Burglary,YEAR_target,WEEK_target,YEAR_WEEK_target,SUB_YEAR_WEEK_target,call_ALL_target,call_Burglary_target
0,2008_38_ZONE1A,16,ZONE1A,38,9,2008,2008_38,3,2008,39,2008_39,2008_39_ZONE1A,33,3.0
1,2008_38_ZONE1B,16,ZONE1B,38,9,2008,2008_38,1,2008,39,2008_39,2008_39_ZONE1B,27,2.0
2,2008_38_ZONE1C,19,ZONE1C,38,9,2008,2008_38,0,2008,39,2008_39,2008_39_ZONE1C,29,1.0
3,2008_38_ZONE1D,17,ZONE1D,38,9,2008,2008_38,1,2008,39,2008_39,2008_39_ZONE1D,47,1.0
4,2008_38_ZONE2A,13,ZONE2A,38,9,2008,2008_38,0,2008,39,2008_39,2008_39_ZONE2A,19,0.0

In [77]:
#droping YEAR_target and WEEK_target" 
df_calls_subweek_target = df_calls_subweek_target.drop(columns=["YEAR_target", "WEEK_target"])

In [78]:
df_calls_subweek_target.head()

,SUB_YEAR_WEEK,call_ALL,Subzone,WEEK,MONTH,YEAR,YEAR_WEEK,call_Burglary,YEAR_WEEK_target,SUB_YEAR_WEEK_target,call_ALL_target,call_Burglary_target
0,2008_38_ZONE1A,16,ZONE1A,38,9,2008,2008_38,3,2008_39,2008_39_ZONE1A,33,3.0
1,2008_38_ZONE1B,16,ZONE1B,38,9,2008,2008_38,1,2008_39,2008_39_ZONE1B,27,2.0
2,2008_38_ZONE1C,19,ZONE1C,38,9,2008,2008_38,0,2008_39,2008_39_ZONE1C,29,1.0
3,2008_38_ZONE1D,17,ZONE1D,38,9,2008,2008_38,1,2008_39,2008_39_ZONE1D,47,1.0
4,2008_38_ZONE2A,13,ZONE2A,38,9,2008,2008_38,0,2008_39,2008_39_ZONE2A,19,0.0

In [79]:
df_calls_subweek_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12169 entries, 0 to 12168
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SUB_YEAR_WEEK         12169 non-null  object
 1   call_ALL              12169 non-null  Int64
 2   Subzone               12169 non-null  object
 3   WEEK                  12169 non-null  UInt32
 4   MONTH                 12169 non-null  int32
 5   YEAR                  12169 non-null  int32
 6   YEAR_WEEK             12169 non-null  object
 7   call_Burglary         12169 non-null  int64
 8   YEAR_WEEK_target      12169 non-null  object
 9   SUB_YEAR_WEEK_target  12169 non-null  object
 10  call_ALL_target       11907 non-null  Int64
 11  call_Burglary_target  11907 non-null  float64
dtypes: Int64(2), UInt32(1), float64(1), int32(2), int64(1), object(5)
memory usage: 1.0+ MB

In [80]:
#droping YEAR_WEEK_target" 
df_calls_subweek_target = df_calls_subweek_target.drop(columns=["YEAR_WEEK_target"])

In [81]:
df_calls_subweek_target.head()

,SUB_YEAR_WEEK,call_ALL,Subzone,WEEK,MONTH,YEAR,YEAR_WEEK,call_Burglary,SUB_YEAR_WEEK_target,call_ALL_target,call_Burglary_target
0,2008_38_ZONE1A,16,ZONE1A,38,9,2008,2008_38,3,2008_39_ZONE1A,33,3.0
1,2008_38_ZONE1B,16,ZONE1B,38,9,2008,2008_38,1,2008_39_ZONE1B,27,2.0
2,2008_38_ZONE1C,19,ZONE1C,38,9,2008,2008_38,0,2008_39_ZONE1C,29,1.0
3,2008_38_ZONE1D,17,ZONE1D,38,9,2008,2008_38,1,2008_39_ZONE1D,47,1.0
4,2008_38_ZONE2A,13,ZONE2A,38,9,2008,2008_38,0,2008_39_ZONE2A,19,0.0

**9.2 Create df_pred_calls**

In [82]:
#Create df_pred_calls by copying the following columns from df_calls_subweek_targe
df_pred_calls = df_calls_subweek_target[
    [
        "SUB_YEAR_WEEK",
        "SUB_YEAR_WEEK_target",
        "call_ALL_target",
        "call_Burglary_target",
    ]
].copy()

In [83]:
#Merge df_pred_calls with df_calls_disp_week
df_pred_calls = pd.merge(
    df_pred_calls,
    df_calls_disp_week,
    how="inner",
    on="SUB_YEAR_WEEK"
)

In [84]:
df_pred_calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12169 entries, 0 to 12168
Columns: 116 entries, SUB_YEAR_WEEK to call_Burglary_comp
dtypes: Int64(2), UInt32(1), float64(21), int32(2), int64(86), object(4)
memory usage: 10.7+ MB

In [85]:
df_pred_calls.head()

,SUB_YEAR_WEEK,SUB_YEAR_WEEK_target,call_ALL_target,call_Burglary_target,call_ALL,Subzone,WEEK,MONTH,YEAR,YEAR_WEEK,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12,call_Armed subject,call_Assault,call_Burglar alarm,call_Burglary,call_Disturbance,call_Domestic,call_FW FIREWORKS,call_Fight,call_Loitering,call_Message delivery,call_Noise complaint,call_Possible drugs present,call_Prowler,call_Public Intoxication,call_Shots fired,call_Special residence patrol,call_Special watch,call_Stalking,call_Suspicious activity,call_Trespassing,call_Vandalism,call_Welfare check,disp_15-ARREST,disp_66-CANCEL,disp_9-VERBAL,disp_ADV-ADVICE GIVEN,disp_AST-ASSIST,disp_CI-CITY CITATION,disp_CLR-CLEARED BY DISPATCH,disp_CM-CIVIL MATTER,disp_COMP,disp_DISR,disp_Disregard,disp_Domestic Violence Report,disp_FA-FALSE ALARM,disp_FD-FOUNDED ALARM,disp_FI-FIELD INTERVIEW,disp_Gone on Arrival,disp_IRT Report,disp_K9 Report,disp_MC-STATE MISD CITATION,disp_MDT-BOLO'D MDT,disp_MSG-MESSAGE DELIVERED,disp_N25-NO CONTACT,disp_NR-NO REPORT,disp_Other,disp_PR-PROPERTY RETURNED,disp_RES-RESOLVED,disp_RF-REPORT FILED,disp_Runaway juvenile (entered NCIC),disp_SAT-SETTLED AMONG SELVES,disp_TES-TEST,disp_TI -TOW IN,disp_Truancy,disp_VA Hospital Alarm (Fire),SqFootage,HousingUnits,Population,Population_Male,Population_Female,Worked,Workers who travel to work,Drove alone to Work,Carpooled to Work,Population_3andover,Enrolled in school,"Enrolled in nursery school, preschool",Enrolled in kindergarten,"Enrolled in college, undergraduate years",Graduate or professional school,Not enrolled in school,Households_earnings,Households_wageorsalaryincome,Households_selfemploymentincome,Households_interest_dividends,Households_SSI,Households_publicassistanceincome,MedianAge_Total,MedianAge_Male,MedianAge_Female,HouseholdIncome_Median,HouseholdIncome_Median_25to44,HouseholdIncome_Median_65andover,HouseholdIncome_Median_45to64,Income_PerCapita,call_ALL_comp,call_Burglary_comp
0,2008_38_ZONE1A,2008_39_ZONE1A,33,3.0,16,ZONE1A,38,9,2008,2008_38,1,0,4,5,4,0,0,0,0,0,0,0,0,0,0,14,0,0,0,1,0,5,3,2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,6,0,0,1,4,0,0,0,0,0,0,2.196943e+07,77,2866,0.481158,0.518842,1097,0.967183,0.830447,0.058341,2763,0.264206,0.020992,0.000000,0.031849,0.027506,0.735794,905,0.955801,0.131492,0.171271,0.181215,0.028729,33,27,40,25994,31089.000000,43746,27679,16862,118.0,7.0
1,2008_38_ZONE1B,2008_39_ZONE1B,27,2.0,16,ZONE1B,38,9,2008,2008_38,6,0,0,5,3,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,2,1,0,2,0,2,0,0,4,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0,6,0,0,2,2,0,0,0,0,0,0,2.330865e+07,68,3417,0.575066,0.424934,2025,0.984198,0.680988,0.225185,3295,0.301062,0.008801,0.004552,0.181184,0.040668,0.698938,1285,1.000000,0.062257,0.178210,0.021790,0.013230,37,38,34,52050,47114.000000,81316,55827,22271,158.0,14.0
2,2008_38_ZONE1C,2008_39_ZONE1C,29,1.0,19,ZONE1C,38,9,2008,2008_38,4,0,6,3,5,0,0,0,0,0,0,0,0,0,0,18,0,0,0,0,2,2,0,0,3,0,0,1,1,1,2,1,0,1,0,0,0,0,0,2,2,0,0,0,0,0,0,1,0,0,0,0,2,2,0,0,1,0,0,0,0,0,2,3,0,0,2,5,0,0,0,0,0,0,6.501904e+06,30,626,0.322684,0.677316,317,1.000000,0.807571,0.164038,606,0.145215,0.044554,0.000000,0.023102,0.000000,0.854785,229,1.000000,0.296943,0.056769,0.165939,0.021834,45,37,46,22150,65078.291667,18068,34792,14181,156.0,15.0
3,2008_38_ZONE1D,2008_39_ZONE1D,47,1.0,17,ZONE1D,38,9,2008,2008_38,4,0,8,2,3,0,0,0,0,0,0,0,0,0,0,17,0,0,0,0,1,2,1,3,1,0,4,0,0,2,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0,0,6,6,0,0,1,1,0,0,0,0,0,0,1.306158e+08,182,4522,0.507519,0.492481,2366,0.988588,0.883770,0.087489,4358,0.267324,0.011014,0.006884,0.109224,0.028683,0.732676,1657,1.000000,0.042245,0.166566,0.064575,0.050694,31,28,32,33225,35873.000000,32084,44433,20857,119.0,9.0
4,2008_38_ZONE2A,2008_39_ZONE2A,19,0.0,13,ZONE2A,38,9,2008,2008_38,2,0,2,7,1,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,2,0,1,2,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0,7,0,0,1,1,0,0,0,0,0,0,6.732244e+07,75,2891,0.578692,0.421308,973,1.000000,0.850976,0.123330,2846,0.165847,0.000000,0.014406,0.031975,0.004216,0.834153,581,1.000000,0.106713,0.092943,0.184165,0.115318,38,39,37,45937,50703.000000,27333,54733,22852,26.0,2.0

In [86]:
df_pred_calls = df_pred_calls.dropna()

In [87]:
df_pred_calls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11907 entries, 0 to 12168
Columns: 116 entries, SUB_YEAR_WEEK to call_Burglary_comp
dtypes: Int64(2), UInt32(1), float64(21), int32(2), int64(86), object(4)
memory usage: 10.5+ MB

**9.3 Create Burg_status and ALL_status**

In [88]:
#For df_pred_calls create a column named ALL_status
df_pred_calls["ALL_status"] = (df_pred_calls["call_ALL_target"] > 0).astype(int)

In [89]:
df_pred_calls[["call_ALL_target", "ALL_status"]].head()

   call_ALL_target  ALL_status
0               33           1
1               27           1
2               29           1
3               47           1
4               19           1

In [90]:
#For df_pred_calls create a column named Burg_status
df_pred_calls["Burg_status"] = (df_pred_calls["call_Burglary_target"] > 0).astype(int)

In [91]:
df_pred_calls[["call_Burglary_target", "Burg_status"]].head()

   call_Burglary_target  Burg_status
0                   3.0            1
1                   2.0            1
2                   1.0            1
3                   1.0            1
4                   0.0            0

In [92]:
df_pred_calls.columns

Index(['SUB_YEAR_WEEK', 'SUB_YEAR_WEEK_target', 'call_ALL_target',
       'call_Burglary_target', 'call_ALL', 'Subzone', 'WEEK', 'MONTH', 'YEAR',
       'YEAR_WEEK',
       ...
       'MedianAge_Female', 'HouseholdIncome_Median',
       'HouseholdIncome_Median_25to44', 'HouseholdIncome_Median_65andover',
       'HouseholdIncome_Median_45to64', 'Income_PerCapita', 'call_ALL_comp',
       'call_Burglary_comp', 'ALL_status', 'Burg_status'],
      dtype='object', length=118)

In [93]:
df_pred_calls[['SUB_YEAR_WEEK','SUB_YEAR_WEEK_target','call_ALL_target','call_Burglary_target','call_ALL_comp','Burg_status', 'ALL_status']].head()

,SUB_YEAR_WEEK,SUB_YEAR_WEEK_target,call_ALL_target,call_Burglary_target,call_ALL_comp,Burg_status,ALL_status
0,2008_38_ZONE1A,2008_39_ZONE1A,33,3.0,118.0,1,1
1,2008_38_ZONE1B,2008_39_ZONE1B,27,2.0,158.0,1,1
2,2008_38_ZONE1C,2008_39_ZONE1C,29,1.0,156.0,1,1
3,2008_38_ZONE1D,2008_39_ZONE1D,47,1.0,119.0,1,1
4,2008_38_ZONE2A,2008_39_ZONE2A,19,0.0,26.0,0,1

**9.4 Summary for Section 9**

In the final step, we have created two binary indicator columns in df_pred_calls to support classification modeling.
The first column, ALL_status, provides information whether at least one call occurred within a given SUB_YEAR_WEEK based on the presence of call_ALL_target.The second column, Burg_status, indicates whether at least one burglary occurred in the same time–subzone unit using call_Burglar_target

Each column has a value of 1 if the condition is met and 0 otherwise. These columns give us great oppertunity to develop classification model. For example, we can treat ALL_Status as our target and ask will there be at least one call in this subzone during the target week?

We can consider Burg_status as target variable for classification problem and ask what is the probability of at least one burglary likely in this subzone next week?
All this information will help the police chief to make better decisions

<h3 style="color:black;"> 10. Save Jupyter Notebook</h3>

Jupyter Notebook has been saved

<h3 style="color:black;"> 11. Submit notebook through Dropbox on D2L</h3>

Notebook has been submitted with proper namming conventions.